#!/usr/bin/env bash

# =============
# SHELL ALIASES
# =============

# +----------------+
# | SYSTEM RELATED |
# +----------------+
alias sudo='sudo ' # Allow aliases to be sudo'ed

# +------------+
# | NAVIGATION |
# +------------+
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias ........="cd ../../../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# +-----------+
# | SHORTCUTS |
# +-----------+
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias dc="cd ~/Documents"
alias dev="cd ~/Development"
alias scratch="cd ~/Development/scratch"
alias repos="cd ~/Development/github.com/pszponder"
alias dot="cd ~/.config"
alias zdot="cd ~/.config/zsh"

# +---------------------+
# | source config files |
# +---------------------+
alias sourcez="source ~/.config/zsh/.zshrc"

# +-----------------+
# | clearing screen |
# +-----------------+
alias cl="clear"

# +----------------------+
# | lsd (ls alternative) |
# +----------------------+
alias ls='lsd'
alias l='ls -l'
alias la='ls -A'
alias lla='ls -lA'

# Specialty views
alias lS='ls -1' # one column, just names
alias lt='ls --tree --depth' # User must specify depth (ex. "lt 2" for 2 levels deep)

# +------+
# | wget |
# +------+
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"'

# +--------------------+
# | copy, move, remove |
# +--------------------+
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'

# +-----+
# | bat |
# +-----+
alias cat='bat --paging=never'

# +------+
# | grep |
# +------+
alias grep='rg --hidden --smart-case --follow --color=always'

alias rgf='rg --files-with-matches --no-messages'  # List files that match
alias rgl='rg --files-without-match --no-messages' # List files that don't match
alias rgg='rg --glob'                              # Search only files matching glob
alias rgi='rg --ignore-case'                       # Case insensitive
alias rgv='rg --invert-match'                      # Invert match
alias rgc='rg --count'                             # Count number of matches
alias rgA='rg --after-context'                     # Shows x number of lines after the match, ex. rgA 2
alias rgB='rg --before-context'                    # Shows x number of lines before the match, ex. rgB 2
alias rgC='rg --context'                           # Shows x number of lines around the match, ex. rgC 2
alias rgw='rg --word-regexp'                       # Only match whole words
alias rgp='rg --pretty'                            # Show results in a more readable format
alias rgs='rg --sort-files'                        # Sort files by name before searching

# +-------+
# | xclip |
# +-------+
alias clipf='xclip -sel clip <' # ex. clipf someFile.txt
alias clip='xclip -selection clipboard' # ex. pwd | clip

# +------+
# | vim |
# +------+
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

# +-----+
# | Git |
# +-----+
# Reference plugin_git.zsh under .config/zsh/plugins for more git aliases

# +---------+
# | lazygit |
# +---------+
alias lg="lazygit"

# +------+
# | MISC |
# +------+
