#!/usr/bin/env zsh

# =========================
# ZSH CONFIGURATION / SETUP
# =========================

# +-----------------+
# | STARSHIP PROMPT |
# +-----------------+
eval "$(starship init zsh)"

# # +--------------------+
# # | PIXI Auto-Complete |
# # +--------------------+
# eval "$(pixi completion --shell zsh)"
