#!/usr/bin/env zsh

# =========================
# ZSH CONFIGURATION / SETUP
# =========================

# +--------------------------+
# | HOMEBREW PACKAGE MANAGER |
# +--------------------------+
# https://brew.sh/
# eval "$(/opt/homebrew/bin/brew shellenv)" # macOS (ARM) specific Homebrew path
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" # Linux specific Homebrew path

# # +-------------------------------+
# # | POWERLEVEL10K ZSH POMPT THEME |
# # +-------------------------------+
# # NOTE: this is installed through brew in this case
# # to configure type p10 configure
# source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
# # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# # Initialization code that may require console input (password prompts, [y/n]
# # confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
# # To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
# [[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# +-----------------+
# | STARSHIP PROMPT |
# +-----------------+
eval "$(starship init zsh)"

# Set the window title
function set_win_title(){
	echo -ne "\033]0; $(basename "$PWD") \007"
}
precmd_functions+=(set_win_title)
starship_precmd_user_func="set_win_title"

# # +-------------------+
# # | OH-MY-POSH PROMPT |
# # +-------------------+
# eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/themes/custom.omp.json)"

# +-------------------------------+
# | MISE POLYGLOT RUNTIME MANAGER |
# +-------------------------------+
# https://mise.jdx.dev/
eval "$(/$HOME/.local/bin/mise activate zsh)"
eval "$(mise hook-env -s zsh)"

# +----------------------+
# | PIXI PACKAGE MANAGER |
# +----------------------+
# https://prefix.dev/
export PATH=$PATH:/$HOME/.pixi/bin

# # +------------------------+
# # | ADVANCED TAB COMPLETION
# # +------------------------+
# # NOTE: This is replaced by Fzf-tab
# autoload -Uz compinit && setopt PROMPT_SUBST && compinit && zstyle ':completion:*' menu select

# +--------+
# | AUTOCD |
# +--------+
# Enable autocd, autopushd, and pushdignoredups options
setopt autocd autopushd pushdignoredups

# +----------+
# | VIM MODE |
# +----------+
bindkey -v

# +----------------------------+
# | ZOXIDE (Better cd command) |
# +----------------------------+
# https://github.com/ajeetdsouza/zoxide
eval "$(zoxide init zsh)"

# +------------------+
# | FZF (fuzzy find) |
# +------------------+
# https://github.com/junegunn/fzf
# https://www.josean.com/posts/7-amazing-cli-tools
eval "$(fzf --zsh)"
alias cd="z"

# -- Use fd instead of fzf --
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
	fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
	fd --type=d --hidden --exclude .git . "$1"
}

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
	local command=$1
	shift

	case "$command" in
		cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
		export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
		ssh)          fzf --preview 'dig {}'                   "$@" ;;
		*)            fzf --preview "bat -n --color=always --line-range :500 {}" "$@" ;;
	esac
}

# +--------------------------------------------------------+
# | The Fuck (correct errors in previous console commands) |
# +--------------------------------------------------------+
# https://github.com/nvbn/thefuck
eval $(thefuck --alias)
eval $(thefuck --alias darn)