#!/usr/bin/env zsh

# =========================
# ZSH CONFIGURATION / SETUP
# =========================

# +--------------------------+
# | HOMEBREW PACKAGE MANAGER |
# +--------------------------+
# https://brew.sh/
if [[ -f "/opt/homebrew/bin/brew" ]]; then
	eval "$(/opt/homebrew/bin/brew shellenv)" # macOS (ARM) specific Homebrew path
elif [[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]]; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" # Linux specific Homebrew path
fi

# # +-------------------------------+
# # | POWERLEVEL10K ZSH POMPT THEME |
# # +-------------------------------+
# # NOTE: this is installed through brew in this case
# # to configure type p10 configure
# source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
# # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# # Initialization code that may require console input (password prompts, [y/n]
# # confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
# # To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
# [[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# +-----------------+
# | STARSHIP PROMPT |
# +-----------------+
# eval "$(starship init zsh)"

# # Set the window title
# function set_win_title(){
# 	echo -ne "\033]0; $(basename "$PWD") \007"
# }
# precmd_functions+=(set_win_title)
# starship_precmd_user_func="set_win_title"

# +-------------------+
# | OH-MY-POSH PROMPT |
# +-------------------+
eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/themes/custom.omp.json)"

# +-------------------------------+
# | MISE POLYGLOT RUNTIME MANAGER |
# +-------------------------------+
# https://mise.jdx.dev/
eval "$(/$HOME/.local/bin/mise activate zsh)"
eval "$(mise hook-env -s zsh)"

# +----------------------+
# | PIXI PACKAGE MANAGER |
# +----------------------+
# https://prefix.dev/
export PATH=$PATH:/$HOME/.pixi/bin

# +-------------+
# | ZSH HISTORY |
# +-------------+
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=5000                    # Maximum events for internal history
export SAVEHIST=$HISTSIZE               # Maximum events in history file
export HISTDUP=erase                    # Erase any duplicates in history file
setopt appendhistory # Append history instead of overwriting
setopt sharehistory # Share ZSH history across all ZSH sessions
setopt hist_ignore_space # prevent command to be written to history file by prepending command with space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups # Prevent duplicates from being shown in historical search

# +--------+
# | AUTOCD |
# +--------+
# Enable autocd, autopushd, and pushdignoredups options
setopt autocd autopushd pushdignoredups

# +-------------+
# | KEYBINDINGS |
# +-------------+
# bindkey -e                            # emacs mode
bindkey '^p' history-search-backward  # Search history w/ existing keyword backwards
bindkey '^n' history-search-forward   # Search history w/ existing keyword forwards
bindkey '^[w' kill-region

# +----------------------------+
# | ZOXIDE (Better cd command) |
# +----------------------------+
# https://github.com/ajeetdsouza/zoxide
eval "$(zoxide init zsh)"

# +--------------------+
# | LESS PAGER OPTIONS |
# +--------------------+
# less shortcuts: https://gist.github.com/awidegreen/3854277
# j/k -- scroll down/up by one line
# h/l -- scroll left/right by one character
# d/u -- scroll down/up by half a page
# b/f -- scroll down/up by a whole page
# g/G -- go to start/end of file
# q   -- quit
# N   -- toggle line numbers
# S   -- toggle line wrapping
# v   -- open file in $EDITOR
# /   -- search forward
# ?   -- search backward
# n/N -- next/previous search result
# m   -- mark a position
# '   -- go to marked position
# &   -- filter lines by a regex
# h   -- help
export LESS='--chop-long-lines --HILITE-UNREAD --ignore-case --incsearch --jump-target=4 --LONG-PROMPT --no-init --quit-if-one-screen --RAW-CONTROL-CHARS --use-color --window=-4'

# +-----------------------------+
# | ZINIT - ZSH Package Manager |
# +-----------------------------+
# https://github.com/zdharma-continuum/zinit

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# +--------------------+
# | ZSH Plugins (CORE) |
# +--------------------+

# Syntax Highlighting
zinit light zsh-users/zsh-syntax-highlighting
# zinit light zdharma-continuum/fast-syntax-highlighting
# zinit wait lucid for \
#  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
#     zdharma-continuum/fast-syntax-highlighting \
#  blockf \
#     zsh-users/zsh-completions \
#  atload"!_zsh_autosuggest_start" \
#     zsh-users/zsh-autosuggestions
bindkey '^f' autosuggest-accept

# Autosuggestions
zinit light zsh-users/zsh-autosuggestions

# Zsh History Substring Search
zinit light zsh-users/zsh-history-substring-search

# Completions
autoload -U compinit && compinit
zinit light zsh-users/zsh-completions
# Load completions (for zsh-completions)
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # Match upper and lowercase
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no

# +---------+
# | VI MODE |
# +---------+
zinit snippet OMZP::vi-mode
# https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/vi-mode/README.md
# VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
VI_MODE_CURSOR_NORMAL=2
VI_MODE_CURSOR_VISUAL=6
VI_MODE_CURSOR_INSERT=5
VI_MODE_CURSOR_OPPEND=0

# +------------------+
# | FZF (fuzzy find) |
# +------------------+

# https://github.com/junegunn/fzf
# https://www.josean.com/posts/7-amazing-cli-tools
eval "$(fzf --zsh)"
alias cd="z"

# FZF Tab / Git plugins
# https://www.josean.com/posts/7-amazing-cli-tools
zinit light Aloxaf/fzf-tab
zinit light junegunn/fzf-git.sh

# FZF Catppuccin Color Theme
# https://github.com/catppuccin/fzf
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

# -- Use fd instead of fzf --
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
	fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
	fd --type=d --hidden --exclude .git . "$1"
}

export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
	local command=$1
	shift

	case "$command" in
		cd)           fzf --preview 'eza --tree --color=always {} | head -200' "$@" ;;
		export|unset) fzf --preview "eval 'echo $'{}"         "$@" ;;
		ssh)          fzf --preview 'dig {}'                   "$@" ;;
		*)            fzf --preview "bat -n --color=always --line-range :500 {}" "$@" ;;
	esac
}

zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# +-----------------+
# | PLUGINS - OTHER |
# +-----------------+

# Oh-my-zshell plugins
# More here: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::aws
zinit snippet OMZP::kubectl
zinit snippet OMZP::kubectx
zinit snippet OMZP::command-not-found

# Zsh You Should Use (Reminds you of your existing aliases)
zinit light MichaelAquilina/zsh-you-should-use

# Zsh System Clipboard
zinit light kutsan/zsh-system-clipboard