[packages.linux.ubuntu.server]
items = ["git", "curl", "vim"]

[packages.linux.ubuntu.workstation]
items = ["git", "curl", "vim"]

[packages.linux.fedora.server]
items = ["git", "curl", "vim"]

[packages.linux.fedora.workstation]
items = ["git", "curl", "vim"]

[packages.linux.fedora_atomic.server]
items = []

[packages.linux.fedora_atomic.workstation]
items = []

[packages.linux.arch.server]
items = [
    # Miscellaneous utilities
    "git",
    "curl",

    # Editors
    "vim",

    # Shells
    "fish",
    "zsh",

    # Containers
    "podman",
    "podman-docker",

    # Fonts
    "ttf-cascadia-code-nerd",
    "ttf-cascadia-mono-nerd",

    # Wayland clipboard utilities
    "wl-clipboard",
]

[packages.linux.arch.workstation]
items = [
    # Miscellaneous utilities
    "git",
    "curl",

    # Editors
    "vim",
    "libreoffice-fresh",
    "obsidian",
	"visual-studio-code-bin",
    "zed",

    # Shells
    "fish",
    "zsh",

    # Containers
    "podman",
    "podman-docker",

    # Fonts
    "ttf-cascadia-code-nerd",
    "ttf-cascadia-mono-nerd",

    # Wayland clipboard utilities
    "wl-clipboard",

    # Terminals
    "ghostty",

    # Browsers
    "helium-browser-bin",
]

[flatpaks]
items = [
    # Add Flatpak application IDs here
    # Example:
    # "com.spotify.Client",
]

[nerdfonts]
items = [
    # Font names must match the GitHub release zip names
    # See: https://www.nerdfonts.com/font-downloads
    "CaskaydiaCove",
    "CaskaydiaMono",
]
