- name: Install server packages from pacman
  pacman:
    name: "{{ arch_server_pacman_packages }}"
    state: present
    update_cache: yes
  when: not workstation | default(false)

- name: Install workstation packages from pacman
  pacman:
    name: "{{ arch_workstation_pacman_packages }}"
    state: present
    update_cache: yes
  when: workstation | default(false)

- name: Ensure yay (AUR helper) is installed
  pacman:
    name: yay
    state: present
    update_cache: yes

- name: Install server AUR packages using yay
  become: true
  become_user: "{{ ansible_user_id }}"
  command: yay -S --noconfirm {{ item }}
  loop: "{{ arch_server_aur_packages }}"
  when: not workstation | default(false)

- name: Install workstation AUR packages using yay
  become: true
  become_user: "{{ ansible_user_id }}"
  command: yay -S --noconfirm {{ item }}"
  loop: "{{ arch_workstation_aur_packages }}"
  when: workstation | default(false)
