- name: Ensure flatpak is installed (Debian)
  apt:
    name: flatpak
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure flatpak is installed (RedHat)
  dnf:
    name: flatpak
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure flatpak is installed (Arch)
  pacman:
    name: flatpak
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Add Flathub remote if not already added
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps from Flathub
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flatpak_apps }}"
  when: flatpak_apps is defined and flatpak_apps | length > 0
