- hosts: localhost
  become: yes

  vars:
    # Arch Linux specific variables
    cli_packages:
      - git
      - curl
      - htop

    gui_packages:
      - gnome-terminal
      - firefox
      - vlc

    flatpak_apps:
      - com.spotify.Client
      - org.gimp.GIMP
      - org.mozilla.firefox

    brew_cask_packages:
      - iterm2
      - firefox
      - vlc

  tasks:
    - name: Ensure Flatpak is installed and configured
      include_tasks: tasks/flatpak.yml
      when: ansible_facts['os_family'] != "Darwin"

    - name: Include tasks for Debian/Ubuntu
      include_tasks: tasks/debian.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Include tasks for Fedora
      include_tasks: tasks/fedora.yml
      when: ansible_facts['os_family'] == "RedHat"

    - name: Include tasks for Arch
      include_tasks: tasks/arch.yml
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install Flatpak and apps on Linux
      include_tasks: tasks/flatpak.yml
      when: ansible_facts['os_family'] != "Darwin"

    - name: Run common Linux tasks (cross-distro)
      include_tasks: tasks/linux_common.yml
      when: ansible_facts['os_family'] != "Darwin"

    - name: Include tasks for macOS
      include_tasks: tasks/darwin.yml
      when: ansible_facts['os_family'] == "Darwin"
