# NOTE: Must install Tmux Plugin Manager (tpm) 1st (https://github.com/tmux-plugins/tpm)

# =================================================================
# HOW TO SOURCE TMUX CONFIG:
# tmux source $XDG_CONFIG_HOME/tmux/tmux.conf
# (or Prefix + r)
#
# HOW TO INSTALL PLUGINS:
# 1. Add new plugin to ".tmux.conf" with "set -g @plugin '...'"
# 2. Press "<tmux prefix> + I" to install plugins from tmux.conf
#
# RESOURCES:
# https://tmuxcheatsheet.com/
# https://www.youtube.com/watch?v=DzNmUNvnB04
# https://github.com/dreamsofcode-io/tmux
# https://github.com/tmux/tmux
# https://github.com/tmux-plugins/tpm
# https://github.com/christoomey/vim-tmux-navigator
# https://github.com/dreamsofcode-io/catppuccin-tmux
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux
# https://dev.to/iggredible/useful-tmux-configuration-examples-k3g
# =================================================================

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

# Change Tmux leader (Prefix) Keybinding
# set -g prefix C-s # Ctrl + s

# Reload tmux.conf (<leader> + r)
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."


# Set mouse support to on
set -g mouse on

# Navigate between different panes in Tmux
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Move TMUX status bar to the top
set-option -g status-position top

# Increase Line Window History
set-option -g history-limit 100000

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Create a new window
# NOTE: To view list of sessions (windows) => tmux ls
bind-key c new-window

# Shift arrow to switch windows (Either Shift + L/R arrow, OR, H/L keys)
bind -n S-Left  previous-window
# bind -n H previous-window
bind -n S-Right next-window
# bind -n L next-window

# Kill current window
bind-key d kill-window

# Use Prefix + | or Prefix + \ for a vertical split (pane)
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

# Use Prefix + - or Prefix + _ for a horizontal split (pane)
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

# Kill current pane
bind-key x kill-pane

# ===================
# Tmux Plugin Manager
# ===================

# List of plugins (to install => <leader> + I)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavour "mocha" # latte or frappe, macchiato, mocha
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory user host session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
