[tools]
bun = "latest"
python = "latest"
rust = "latest"
go = "latest"
chezmoi = "latest"
node = "latest"
tmux = "latest"
devcontainer-cli = "latest"
fd = "latest"
zoxide = "latest"
uv = "latest"
jq = "latest"
github-cli = "latest"
neovim = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
fzf = "latest"
ripgrep = "latest"
starship = "latest"
bat = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
atuin = "latest"
"github:block/goose" = "latest"
ruff = "latest"
ty = "latest"
opencode = "latest"
jj = "latest"
gemini-cli = "latest"
codex = "latest"
crush = "latest"
"npm:@github/copilot" = "latest"
"github:max-sixty/worktrunk" = "latest"
btop = "latest"
zellij = "latest"
